### ISSUE TITLE
Replace stodevx/sga with carls-app/csa references

### ISSUE THREAD

**Issue by drewvolz** [carls-app/weekly-movie-tools#1]

**Comment by hawkrives** [comment]
Do you have any offhand? I believe they're all fixed.

**Comment by hawkrives** [comment]
oh wrong repo

**Comment by drewvolz** [comment]
Yeah. The readme lists things about StoDevX, St. Olaf, and SGA. We should replace them with carls-app, Carleton, and CSA.

**Comment by hawkrives** [comment]
I thought this was in https://github.com/carls-app/carls when I made my first comment; yes, we should clean up those references.
